import { useState, type ReactNode } from 'react';
import { Link, Route, Routes, useLocation } from 'react-router-dom';
import { Activity, ArrowUpRight, Check, CircleDollarSign, FileText, LayoutDashboard, ShieldCheck, Sparkles, Target, Users, X, Zap, type LucideIcon } from 'lucide-react';
import { api } from './lib/api';
import { Button } from './components/ui/Button';
import { Card } from './components/ui/Card';

const strategy = { title: 'Upsell Shoes + Socks', type: 'UPSELL', revenue: 62000, discount: 5, confidence: 94 };

export default function App() {
  return <div className="app"><Routes><Route path="*" element={<Shell />} /></Routes></div>;
}

function Shell() {
  const location = useLocation();
  const pages: Array<readonly [string, string, LucideIcon]> = [['/', 'Overview', LayoutDashboard], ['/planner', 'Goal planner', Target], ['/strategies', 'AI strategies', Sparkles], ['/customers', 'Customers', Users], ['/campaigns', 'Campaign center', Zap], ['/payments', 'Payments', CircleDollarSign], ['/audit', 'Audit trail', ShieldCheck], ['/settings', 'Settings', FileText]];
  return <><aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={18}/></span><span>merchant<br/><b>autopilot</b></span></div><nav>{pages.map(([path, label, Icon]) => <Link className={location.pathname === path ? 'nav-item active' : 'nav-item'} to={path} key={path}><Icon size={17}/><span>{label}</span></Link>)}</nav></aside><main><header><p className="eyebrow">MONDAY, AUGUST 24, 2026</p><h1>{pages.find(page => page[0] === location.pathname)?.[1] || 'Merchant Autopilot'}</h1></header><Routes><Route path="/" element={<Dashboard/>}/><Route path="/strategies" element={<Strategies/>}/><Route path="/payments" element={<Payments/>}/><Route path="/planner" element={<Planner/>}/><Route path="*" element={<Generic/>}/></Routes></main></>;
}
function Dashboard(){ return <Page title="Overview"><Card className="payment-state"><Sparkles size={28}/><h3>Revenue autopilot is ready</h3><p>Review an explainable campaign, approve it, and create a Test Mode payment link.</p><Link className="primary" to="/strategies">Review strategies <ArrowUpRight size={16}/></Link></Card></Page>; }
function Strategies(){ const [status,setStatus]=useState('PENDING_APPROVAL'); return <Page title="AI strategies"><Card className="strategy-card"><div className="strategy-number">01</div><div className="strategy-main"><span className="type-tag">{strategy.type}</span><span className="confidence"><span className="pulse"/>{strategy.confidence}% confidence</span><h3>{strategy.title}</h3><p>1,284 Champions bought footwear recently. Socks are the highest-affinity add-on.</p><div className="strategy-stats"><span><small>Expected revenue</small><b>₹62,000</b></span><span><small>Offer</small><b>5% discount</b></span><span><small>Margin impact</small><b className="positive">Protected</b></span></div><div className="why"><Sparkles size={15}/><span><b>Why selected</b>Strong product affinity and high-intent timing.</span></div></div><div className="strategy-action">{status === 'PENDING_APPROVAL' ? <><Button onClick={() => setStatus('APPROVED')}>Approve campaign <Check size={16}/></Button><button className="reject" onClick={() => setStatus('REJECTED')}><X size={15}/> Reject</button></> : <div className={status === 'APPROVED' ? 'approved large' : 'rejected-label'}>{status === 'APPROVED' ? <><Check size={16}/> Approved</> : <><X size={15}/> Rejected</>}</div>}</div></Card></Page>; }
function Payments(){ const [status,setStatus]=useState('READY'); const [link,setLink]=useState(''); const [orderId,setOrderId]=useState(''); const [events,setEvents]=useState<string[]>([]); const [paymentId,setPaymentId]=useState('demo-link'); async function create(){ setStatus('CREATING'); const result=await api.createPaymentLink({campaignId:'00000000-0000-0000-0000-000000000001',amountPaise:6200000,description:strategy.title}); setStatus(String(result.status)); setLink(String(result.shortUrl)); setPaymentId(String(result.paymentLinkId || 'demo-link')); setOrderId(String(result.orderId || `demo-order-${Date.now()}`)); setEvents(['Link created']); } async function expire(){ const result=paymentId !== 'demo-link' ? await api.expirePayment(paymentId) : {status:events.includes('Retry initiated')?'STOPPED':'RETRY_REQUIRED'}; const next=String(result.status); setStatus(next); setEvents(old => [...old, ...(next === 'RETRY_REQUIRED' ? ['Payment expired','Retry initiated'] : ['Retry failed','Campaign stopped'])]); } return <Page title="Payments"><Card className="payment-state"><CircleDollarSign size={28}/><h3>Razorpay Test Mode</h3><p>Create a link after campaign approval, then simulate failure handling for the judging demo.</p>{status === 'READY' ? <Button onClick={create}><CircleDollarSign size={16}/> Generate payment link</Button> : <><div className="payment-result"><div><span>Status</span><b>{status}</b></div><div><span>Order ID</span><b>{orderId}</b></div></div>{link && <a className="payment-link" href={link} target="_blank" rel="noreferrer">Open Test Mode checkout <ArrowUpRight size={15}/></a>}{status !== 'STOPPED' && <button className="small-button expire-button" onClick={expire}>Simulate expiration</button>}{events.length > 0 && <div className="failure-timeline"><b>Payment event timeline</b>{events.map((event,index)=><div key={`${event}-${index}`}><span>{['10:01','10:15','10:16','10:40','10:41'][index] || 'Now'}</span>{event}</div>)}</div>}</>}</Card></Page>; }
function Planner(){ return <Page title="Goal planner"><Card className="payment-state"><Target size={28}/><h3>Set your revenue goal</h3><p>Enter ₹2,00,000 with a 5% maximum discount and 35% minimum margin to generate the strict plan.</p><Link className="primary" to="/strategies">Open AI strategies <ArrowUpRight size={16}/></Link></Card></Page>; }
function Generic(){ return <Page title="Merchant workspace"><Card className="payment-state"><Activity size={28}/><h3>Live data workspace</h3><p>Connect the backend to populate this view.</p></Card></Page>; }
function Page({title,children}:{title:string;children:ReactNode}){ return <section className="page-content page-enter"><div className="page-title"><div><span className="eyebrow">MERCHANT AUTOPILOT</span><h2>{title}</h2><p>Explainable revenue actions with merchant approval at the center.</p></div></div>{children}</section>; }
